#!/bin/sh /etc/rc.common

START=99

start () {
    DOMAINS_ANTIFILTER=https://github.com/MrYadro/domain-list-community-antifilter/releases/latest/download/dlc.dat

    curl -fL $DOMAINS_ANTIFILTER -o /usr/share/xray/antifilter.dat

    DOMAINS_COMMUNITY=https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat

    curl -fL $DOMAINS_COMMUNITY -o /usr/share/xray/community.dat
}
