#!/bin/sh /etc/rc.common

START=99

start () {
    DOMAINS=https://github.com/MrYadro/domain-list-community-antifilter/releases/latest/download/dlc.dat

    curl -fL $DOMAINS -o /usr/share/xray/dlc.dat
}